"""create resumes table

`resumes` is a 0..1 structured extension of `students` (unique
`student_id` FK, `ON DELETE CASCADE`) — a student may have at most one
resume profile, created explicitly (there is no auto-provisioning here,
unlike `students` itself — see docs/resume-module.md for why). No
authentication or profile fields (email, full_name, department, cgpa,
skills, etc.) are duplicated here; this table only holds resume-specific
structured content for the MVP (`professional_summary`,
`career_objective`). No enum types are involved, so no orphaned-type
cleanup is needed on downgrade (unlike the users/skills migrations).

Revision ID: 04b4acaa5c64
Revises: 38f0da1163aa
Create Date: 2026-09-09 04:36:06.477331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b4acaa5c64'
down_revision: Union[str, None] = '38f0da1163aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('professional_summary', sa.String(length=2000), nullable=True),
    sa.Column('career_objective', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_student_id'), 'resumes', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_student_id'), table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
