"""create departments and students tables

`departments` is a small lookup table — students reference an existing
department by id rather than entering free text. Seeded here with a
starter set of common department names so the feature is usable out
of the box; more can be added later via a normal data migration or an
admin endpoint (not yet implemented).

`students` is a 1:1 profile extension of `users` (unique `user_id` FK,
`ON DELETE CASCADE`) — authentication fields (email, password, role,
is_active) stay on `users` and are not duplicated here.

Revision ID: 2ebd1e570480
Revises: c227557a7841
Create Date: 2026-08-12 19:55:44.977480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebd1e570480'
down_revision: Union[str, None] = 'c227557a7841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Starter department list — seeded as data (not hardcoded IDs anywhere
# in application code), so it's easy to extend later without touching
# this migration again.
_SEED_DEPARTMENTS = [
    "Computer Applications",
    "Computer Science and Engineering",
    "Information Technology",
    "Electronics and Communication Engineering",
    "Mechanical Engineering",
    "Business Administration",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    # ### end Alembic commands ###

    # Not auto-generated: seed a starter set of departments so the
    # lookup table isn't empty out of the box.
    departments_table = sa.table(
        'departments',
        sa.column('name', sa.String),
    )
    op.bulk_insert(departments_table, [{"name": name} for name in _SEED_DEPARTMENTS])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
