"""add placements table

Revision ID: 5691ad76ea38
Revises: dd9cdd2a8b78
Create Date: 2026-09-29 20:55:56.625237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5691ad76ea38'
down_revision: Union[str, None] = 'dd9cdd2a8b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('final_package_ctc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('placement_date', sa.Date(), nullable=False),
    sa.Column('offer_accepted', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placements_application_id'), 'placements', ['application_id'], unique=True)
    op.create_index(op.f('ix_placements_id'), 'placements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placements_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_application_id'), table_name='placements')
    op.drop_table('placements')
    # ### end Alembic commands ###
