"""create skills and student_skills tables

`skills` is a small platform-level lookup/catalog table — students
pick from an existing skill rather than each creating arbitrary
duplicate entries (same pattern as `departments`). Seeded here with a
starter catalog of common skills relevant to a placement-analytics
platform, so the feature is usable out of the box.

`student_skills` is the many-to-many association between `students`
and `skills`, carrying the student's self-reported proficiency for
that skill. A unique constraint on (student_id, skill_id) prevents a
student from adding the same skill twice; `ON DELETE CASCADE` on both
foreign keys means a deleted student profile or catalog skill takes
its assignment rows with it.

Revision ID: 70466c0ad0bf
Revises: 2ebd1e570480
Create Date: 2026-08-25 02:39:15.900128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70466c0ad0bf'
down_revision: Union[str, None] = '2ebd1e570480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Starter skill catalog — seeded as data (not hardcoded IDs anywhere
# in application code), so it's easy to extend later without touching
# this migration again. Categories are a light grouping, not an enum
# (matches `skills.category` being a free string column).
_SEED_SKILLS = [
    ("Python", "Programming Language"),
    ("Java", "Programming Language"),
    ("JavaScript", "Programming Language"),
    ("TypeScript", "Programming Language"),
    ("SQL", "Programming Language"),
    ("React", "Framework"),
    ("Node.js", "Framework"),
    ("FastAPI", "Framework"),
    ("Django", "Framework"),
    ("PostgreSQL", "Database"),
    ("MongoDB", "Database"),
    ("Git", "Tool"),
    ("Docker", "Tool"),
    ("AWS", "Cloud"),
    ("Azure", "Cloud"),
    ("Machine Learning", "Data Science"),
    ("Data Analysis", "Data Science"),
    ("Power BI", "Data Science"),
    ("Excel", "Data Science"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='proficiency_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skills_student_id_skill_id')
    )
    op.create_index(op.f('ix_student_skills_student_id'), 'student_skills', ['student_id'], unique=False)
    # ### end Alembic commands ###

    # Not auto-generated: seed a starter skill catalog so the lookup
    # table isn't empty out of the box.
    skills_table = sa.table(
        'skills',
        sa.column('name', sa.String),
        sa.column('category', sa.String),
    )
    op.bulk_insert(
        skills_table,
        [{"name": name, "category": category} for name, category in _SEED_SKILLS],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_skills_student_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
    # Not auto-generated: drop_table does not drop the native
    # PostgreSQL enum type it depended on, so it would otherwise be
    # left orphaned (same fix as the `user_role` enum in the users
    # migration).
    sa.Enum(name='proficiency_level').drop(op.get_bind(), checkfirst=True)
