"""Add application rounds

Revision ID: 81798731b236
Revises: 5691ad76ea38
Create Date: 2026-09-29 21:33:18.260819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81798731b236'
down_revision: Union[str, None] = '5691ad76ea38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.Enum('Online Assessment', 'Coding Test', 'Aptitude Test', 'Technical Interview', 'Managerial Interview', 'HR Interview', 'Group Discussion', 'Other', name='round_type'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('Not Started', 'Scheduled', 'In Progress', 'Completed', 'Cancelled', name='round_status'), server_default='Not Started', nullable=False),
    sa.Column('result', sa.Enum('Pending', 'Passed', 'Failed', 'Not Attended', name='round_result'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'round_number', name='uq_application_rounds_app_id_round_num')
    )
    op.create_index(op.f('ix_application_rounds_application_id'), 'application_rounds', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_rounds_application_id'), table_name='application_rounds')
    op.drop_table('application_rounds')
    # ### end Alembic commands ###
