"""add resume file metadata columns

Extends `resumes` with optional uploaded-file metadata: `file_name`
(original filename, for display/download), `file_path` (relative path
under the configured upload root — internal only, never exposed via
the API), `file_type` (declared content type), `file_size` (bytes).
All four nullable — a resume may have no file uploaded, and existing
resumes created before this migration have none. The actual file
content is never stored in PostgreSQL; only this metadata lives here
(see app.modules.resumes.storage for the filesystem side).

Fully reversible: dropping these four columns loses no other data.

Revision ID: 995c78159606
Revises: 04b4acaa5c64
Create Date: 2026-09-22 02:38:45.892087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995c78159606'
down_revision: Union[str, None] = '04b4acaa5c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('file_type', sa.String(length=100), nullable=True))
    op.add_column('resumes', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'file_type')
    op.drop_column('resumes', 'file_path')
    op.drop_column('resumes', 'file_name')
    # ### end Alembic commands ###
